package io.vito.ludwieg

/**
 * InvalidLengthIdentifierException indicates that encoded metadata about the size of a
 * length-prefixed value could not be parsed. This may indicate that the data is corrupted,
 * malformed, or has been generated by an unsupported protocol version.
 */
class InvalidLengthIdentifierException : Exception()

/**
 * InvalidLengthValueException indicates that the size being encoded does not fit any possible
 * encoding format.
 */
class InvalidLengthValueException : Exception()

/**
 * InvalidUUIDValueException indicates that the input value for generating or parsing an [UUID]
 * instance did not conform to the class expectation.
 *
 * [String]: Must be non-null, and conform to the expression `/^[0-9a-f]{32}$/i`, ignoring dashes.
 * [ByteArray]: Must be non-null and 16-byte long.
 * [java.util.UUID]: Must be non-null.
 */
class InvalidUUIDValueException : RuntimeException()

/**
 * CannotEncodeUnknownTypeException indicates that there was an illegal attempt at encoding a
 * [io.vito.ludwieg.types.TypeUnknown] instance.
 */
class CannotEncodeUnknownTypeException : Exception()

/**
 * InvalidSerializationCandidateException indicates that a serialization candidate does not conform
 * to the framework expectations. It may be raised in the following conditions:
 *
 * 1. The serialization candidate contains fields annotated with [LudwiegField] that does not return
 * an [io.vito.ludwieg.types.Type] value.
 * 2. The serialization candidate is not an instance of a class annotated with [LudwiegPackage]
 * 3. The serialization candidate is not an instance of a class annotated with [Serializable]
 *
 */
class InvalidSerializationCandidateException(msg : String? = null) : Exception(msg)

/**
 * InvalidArrayTypeException indicates that an array being serialized contains invalid metadata, and
 * is thrown in the following conditions:
 *
 * 1. When a [io.vito.ludwieg.types.TypeArray] field annotation does not define its
 * [LudwiegField.arrayType].
 * 2. When a [io.vito.ludwieg.types.TypeArray] contains an instance of [io.vito.ludwieg.types.TypeAny]
 */
class InvalidArrayTypeException(msg: String) : Exception(msg)

/**
 * InvalidArraySizeException indicates that the size of an array field is invalid. Array sizes might
 * be represented using numbers or an asterisk (`*`), if the value is dynamic. For further
 * information, please refer to the framework documentation.
 */
class InvalidArraySizeException(msg : String? = null) : Exception(msg)

/**
 * InvalidTypeException indicates that an operation regarding special types found an unexpected type
 * or condition. It may happen in the following scenarios:
 *
 * 1. A `package` being registered through [Registry.register] is not annotated with [LudwiegPackage]
 * 2. An internal inconsistency caused an [io.vito.ludwieg.types.Type]-based class to lack an
 * [LudwiegInternalType] field.
 */
class InvalidTypeException(msg : String? = null) : Exception(msg)

/**
 * IllegalInvocationException is used internally to prevent special transit types from being encoded
 * or incorrectly handled. Operations throwing this exception includes:
 *
 * 1. Attempts to serialize [io.vito.ludwieg.types.TypeStructBuffer] or a
 * [io.vito.ludwieg.types.TypeArrayBuffer]
 * 2. Attempts to internally coerce data from a non-[io.vito.ludwieg.types.TypeStructBuffer]
 *
 * This exception is used to control internal mechanisms and should not happen in a stable,
 * production environment.
 */
class IllegalInvocationException(msg: String) : Exception(msg)

/**
 * InternalInconsistencyException indicates that an internal inconsistency has been found. Currently,
 * it is used to detect lack of generic information when handling Arrays of Structs. Just like
 * [IllegalInvocationException], this exception should not happen in a stable, production environment.
 */
class InternalInconsistencyException(msg: String) : Exception(msg)

/**
 * InvalidAnyValueException is used to prevent illegal operations on [io.vito.ludwieg.types.TypeAny]
 * values.
 * The framework, by design, prohibits `Any` values from representing instances of:
 *  - [io.vito.ludwieg.types.TypeAny]
 *  - [io.vito.ludwieg.types.TypeStruct]
 *  - Empty [io.vito.ludwieg.types.TypeArray]
 *  - [io.vito.ludwieg.types.TypeArray] retaining [io.vito.ludwieg.types.TypeStruct]s
 */
class InvalidAnyValueException(msg: String) : Exception(msg)
